name: Auto-merge Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run flake8 and pylint
        run: |
          flake8 --ignore=E501,E231 *.py tests/*.py
          pylint --errors-only --disable=C0301,C0326 *.py tests/*.py
      
      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  merge:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Auto-approve PR
        if: github.actor == 'jmgrd98'
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge PR
        if: github.actor == 'jmgrd98'
        uses: managedkaos/merge-pull-request@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
